server:
  port: 8084

spring:
  application:
    name: cloud-provider4
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-interval: 10s
        instance-id: cloud-provider4
        service-name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
