server:
  port: 8081

spring:
  application:
    name: cloud-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-interval: 10s
        instance-id: cloud-provider1
        service-name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

#http://localhost:8500/v1/agent/service/deregister/consul-cloud